# Auto-provision Prometheus as a datasource in Grafana
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-infra:9090
    isDefault: true
    editable: false
